name: clix_flutter
description: Flutter SDK for Clix service - customer engagement platform with push notifications and analytics
version: 0.0.1
homepage: https://clix.so
repository: https://github.com/clix-so/clix-flutter-sdk

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  uuid: ^4.3.3
  crypto: ^3.0.3
  firebase_messaging: ^15.1.3
  permission_handler: ^11.3.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  plugin:
    platforms:
      android:
        package: so.clix
        pluginClass: ClixPlugin
      ios:
        pluginClass: ClixPlugin
