name: clix_flutter
description: Clix - Clix - Mobile push for builders

version: 0.0.1
homepage: https://clix.so
repository: https://github.com/clix-so/clix-flutter-sdk

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  pigeon: ^22.6.0

flutter:
  plugin:
    platforms:
      android:
        package: so.clix
        pluginClass: ClixPlugin
      ios:
        pluginClass: ClixPlugin
