name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "samples/**"
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "samples/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Install dependencies
      run: make get

    - name: Run Format Check
      run: make format

    - name: Run Lint
      run: make lint

    - name: Run Tests
      run: make test

    - name: Run Build
      run: make build
