name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "samples/**"
      - "README.md"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Install dependencies
      run: make get

    - name: Format check
      run: make format

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Build
      run: make build
